### ISSUE TITLE
Stuck at 100% [with workaround]

### ISSUE THREAD

**Issue by nick-scott** [CHollingworth/Lamp#12]
After deploying mods, the game doesnt load and is stuck at 100%

This is a known issue with other mod managers and the fix is to add:
```
<node id="ModuleShortDesc">
    <attribute id="Folder" value="GustavDev" type="LSString"/>
    <attribute id="MD5" value="" type="LSString" />
    <attribute id="Name" value="GustavDev" type="LSString" />
    <attribute id="UUID" value="28ac9ce2-2aba-8cda-b3b5-6e922f71b6b8" type="FixedString" />
    <attribute id="Version64" value="36028797018963968" type="int64" />
</node>
```
to the the mod nodes in  `AppData/Local/Larian Studios/Baldurs Gate 3/PlayerProfiles/Public/modsettings.lsx`

**Comment by CHollingworth** [comment]
Ive pinned this for now and ill leave it open as its a good quick fix that ill implement in the next minor patch.
