### ISSUE TITLE
Work around mods with non-standard archive structure

### ISSUE THREAD

**Issue by alterNERDtive** [CHollingworth/Lamp#15]
This applies mostly to `bin`/`Data` overwrites, but also to some `.pak` mods.

Lots of mods (sadly) have a file structure of e.g. `<mod name>/bin/[…]` instead of flat `bin/[…]` inside the mod archive. Yes, it’s annoying to support “wrong” data structures, but some leeway would be nice. E.g. you could check for `*/[bin|Data]/*` or something.

**Comment by CHollingworth** [comment]
I'm already working on a work arround for FO4 mods, I'll see if the code
works for BG3.
