### ISSUE TITLE
Can not clone git repository

### ISSUE THREAD

**Issue by Bilskirnir3124** [CHollingworth/Lamp#162]
**Describe the bug**

I can not clone the git repository to build the program from source.

**Error message**

Cloning into '/home/[user]/.lampray'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

**To Reproduce**

Run, "git clone git@github.com:CHollingworth/Lampray.git ~/.lampray"

**Expected behaviour**
I expect that I would be able to clone the repository as per the instructions in this very project under, "Building from source."

**Screenshots**
N/A

**System Info (please complete the following information):**
 - Linux Flavour: Arch
 - Window Manager: MATE
 - Lamp Version: 1.3.2

**Comment by ClarinetInALeatherJacket** [comment]
try 
``` 
git clone https://github.com/CHollingworth/Lampray.git 
```

**Comment by Bilskirnir3124** [comment]
Thank you. That did the job. Closing the issue.

**Comment by alterNERDtive** [comment]
For cloning via SSH you have to set up an SSH key in your Github settings.
