### ISSUE TITLE
I think this could be made a little more clear (maybe have an example as a tool tip)

### ISSUE THREAD

**Issue by StuffOfSonny** [CHollingworth/Lamp#18]
![image](https://github.com/CHollingworth/Lamp/assets/61560546/d1d9f20b-fb7e-4d2e-8630-1727514d3c0e)
(note: the "??" in the file path is "🎮", but the program does not know how to display emojis)

**Comment by CHollingworth** [comment]
Ah that it will, in this case the appdata directory needs to be the games app data directory, ill add some tool tips in the next hotfix

**Comment by StuffOfSonny** [comment]
may I still ask for a bit more clarification on "the game's app data"? do you mean the "Larion Studios" folder?

**Comment by CHollingworth** [comment]
Ah apologies the bg3 folder in that folder
