### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by GraithTiger** [CHollingworth/Lamp#20]
Instructions are unclear on how to build.

Installing all the dependencies and using:
```
cmake .
make
```
compiles successfully & produces an executable, but is significantly smaller than the released binary, and coredumps shortly after launching.

I'm building on Arch Linux and have deps `vulkan-headers`, `glfw`, `p7zip`, `zenity`, `pugixml`, `curl`, & `cmake` installed. The released binary works as well.

**Comment by CHollingworth** [comment]
That's certainly a tricky one, you say vulkanheaders I'm assuming you used
sudo pacman -S vulkan-devel
As its the largest libary I can think of that would cause significant size
decrease

**Comment by GraithTiger** [comment]
Compiling with debug symbols enabled, and running with GDB, I get

```
[New Thread 0x7fffebbff6c0 (LWP 170706)]                                                                                                  
[New Thread 0x7fffeb3fe6c0 (LWP 170707)]
[New Thread 0x7fffeabfd6c0 (LWP 170708)]
[New Thread 0x7fffea3fc6c0 (LWP 170709)]
[New Thread 0x7fffe9bfb6c0 (LWP 170710)]
[LAMP:LOG:0] Initializing Lamp FileSystem
[LAMP:LOG:0] Creating Game directories
[LAMP:LOG:0] LAMP CONFIG
[LAMP:LOG:0] Baldur's Gate 3
[LAMP:LOG:0] Finished creating Game directories
[LAMP:LOG:0] Loading Lamp Config
[LAMP:LOG:0] Loading LAMP CONFIG:ShowIntroMenu
[LAMP:LOG:0] Loading LAMP CONFIG:CurrentGame
[LAMP:ERROR:0] Could not load modlist.
[LAMP:LOG:0] Loading Baldur's Gate 3:installDirPath
[LAMP:ERROR:0] Unable to load Baldur's Gate 3:installDirPath
[LAMP:LOG:0] Loading Baldur's Gate 3:appDataPath
[LAMP:ERROR:0] Unable to load Baldur's Gate 3:appDataPath
[New Thread 0x7fffe93fa6c0 (LWP 170711)]
[Thread 0x7fffe9bfb6c0 (LWP 170710) exited]
Lamp: /usr/src/debug/lamp/Lamp-1.0.3.2/imgui/imgui_impl_glfw.cpp:535: bool ImGui_ImplGlfw_Init(GLFWwindow*, bool, GlfwClientApi): Assertion `io.BackendPlatformUserData == nullptr && "Already initialized a platform backend!"' failed.

Thread 1 "Lamp" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
Downloading source file /usr/src/debug/glibc/glibc/nptl/pthread_kill.c
44            return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;         
```

**Comment by CHollingworth** [comment]
Now that is, very strange, from reading the errors, ImGui_ImplGlfw_Init seems to be getting called twice or early, as this is what would cause the assert error. inside imgui_impl_glfw could you uncomment line 536. if this printf doesnt get called or called twice i may need to consider swapping imgui backends for arch.

**Comment by CHollingworth** [comment]
it may be worth downloading imgui-1.89.8 and changing the backends on your side to see which will compile sucsesfully. it may be that i move from vulkan to opengl2 or 3

**Comment by GraithTiger** [comment]
Updated my build script to:
```
  cmake \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_SHARED_LIBS=ON \
    -S. \
    -B build
  cmake --build build
```

The binary is much larger now (~14.5 MB), however I'm still seeing a segfault or abort right after the program initializes. Commenting the lines in `imgui_impl_glfw.cpp` & `imgui_impl_vulkan.cpp` throws  new errors:

`malloc(): smallbin double linked list corrupted'

&

`lamp: /usr/src/debug/lamp/Lamp-1.0.6/imgui/imgui.cpp:9200: void ImGui::ErrorCheckNewFrameSanityChecks(): Assertion `(g.FrameCount == 0 || g.FrameCountEnded == g.FrameCount) && "Forgot to call Render() or EndFrame() at the end of the previous frame?"' failed.`

The released binary for 1.0.6 still runs without crashing though.

**Comment by CHollingworth** [comment]
Id recommend having ago using ninja (i use clion) my build script looks like this.

`cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=/snap/clion/250/bin/ninja/linux/x64/ninja -G Ninja -S /home/c/DEV/Lamp -B /home/c/DEV/Lamp/cmake-build-debug`

**Comment by CHollingworth** [comment]
Build instructions will be added to the wiki
