### ISSUE TITLE
Persistent data location

### ISSUE THREAD

**Issue by GraithTiger** [CHollingworth/Lamp#21]
Currently Lamp produces a `Lamp_Data` directory & `imgui.ini` file in the directory it was launched from, and will show an error and create new files if they don't exist.

It may cause fewer headaches to use `$XDG_CONFIG_HOME` (\~/.local/share) or `$XDG_DATA_HOME` (~/.config) as defined in the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), at least as a fallback if those files don't exist in the runtime directory.

**Comment by CHollingworth** [comment]
Sounds like i plan, ill add it to 1.1.0 goals

**Comment by poperigby** [comment]
@CHollingworth was this ever completed? It seems to still do this.
