### ISSUE TITLE
Feature Request: Game Addition

### ISSUE THREAD

**Issue by Azurion42** [CHollingworth/Lamp#22]
Was just tossing this into the ring for potential future updates by adding Cyberpunk 2077 to the mod manager. Not now or soon, obviously, but after all the other stuff that's on the list is taken care of.

**Comment by CHollingworth** [comment]
Id love to, however im unfamilliar with Cyberpunks mods as ive not played the game, it may be worth considering making a fork and building out a game-data for it Although id wait until 1.1.0 as im adding alot more functions to make building them out easier

**Comment by MattSturgeon** [comment]
Initial Cyberpunk support should be pretty simple. Most mod installation is just a case of deploying the files into the game's install directory.

There are two main types of Cyberpunk mods; traditional  "archive" mods and "RedMod" mods.

RedMod mods are less common, support custom load orders and may require running the `redmod` exe as part of a deployment stage. However, RedMod integration could be a separate stretch goal as a) RedMod mods are uncommon (and usually have a non-RedMod alternative) and b) a user wishing to use RedMod should be able to do any extra steps manually.

**Comment by MattSturgeon** [comment]
> RedMod is also not really supported by linux, Ive tried using it before by itself and in tandem with red4ext, redscript, tweakxl and theblike and it always breaks.

RedMod has worked fine for me using wine/vortex in the past, though I did have issues with the 2.0 update.

As for the file structure, most mods are archived with the files already placed in the correct directories.

I think vortex does do some "smarter" checks, so if the mod archive doesn't have a directory structure it tries to guess where to put them. But like I said, _most_ mods do contain the directory structure.

**Comment by CHollingworth** [comment]
Id need somone to show me the standard directories mods goto(and their extensions), and cyberpunks structure and ill make a test

**Comment by Azurion42** [comment]
.archive files go into Cyberpunk 2077/archive/pc/mod/
red4ext folder goes into Steam/steamapps/common/Cyberpunk 2077/
r6 folder goes into the Steam/steamapps/common/Cyberpunk 2077/
bin folder goes into Steam/steamapps/common/Cyberpunk 2077/
engine folder goes into Steam/steamapps/common/Cyberpunk 2077/
REDMod folder goes into Steam/steamapps/common/Cyberpunk 2777/ 
no mods go into the compatdata folder

This is my install location for my Cyberpunk 2077 game on my home drive. I don't know about flatpaks but I assume it's similar to others, I'm using a native install since I'm on Fedora 38. 

/home/[user]/.local/share/Steam/steamapps/common/Cyberpunk 2077/

Mods like Cyber Engine Tweaks, Codeware, ArchiveXL, TweakXL, EquipmentXL, Red4EXT and similar all have their folder structures set up so that all you have to do is unzip them into the root folder and they go where they need to go. a few mods need to be manually installed simply because they're packed with a LOT of different options that need something like FOMOD to install, or do so manually.

**Comment by CHollingworth** [comment]
Do they use fomod?

**Comment by MattSturgeon** [comment]
> Do they use fomod?

No, haven't seen any Cyberpunk mods using FOMOD, although technically there's no reason why they couldn't.

> a few mods need to be manually installed 

A lot of Cyberpunk mods _claim_ that they should be manually installed. However I haven't found a single mod that didn't work correctly with Vortex. I found one mod that needed to be installed using the "Unpack As-Is" option because something was confusing Vortex's mod-file detection script. I believe many people simply do not understand how Vortex works or how to use it.

> `.archive` files go into `archive/pc/mod`

This is probably the only thing to check; does the mod contain `.archive` files not already nested in a directory structure. Almost all mods package their **files already in the correct structure,** but there are a few that just zip up the mod archives and then tell the end-user to move them into `archive/pc/mod`.

**Comment by Azurion42** [comment]
what I meant by a few mods needing to be manually installed was they don't have the archive>pc>mod folder architecture in the zip/rar/7z file, so you have to manually place them in there. I don't use fomod cause I've never been able to get it to work on Linux. It'd work once, then never start up again.

**Comment by CHollingworth** [comment]
Alright seems like well have to wait for the filesystem update as it will need the ability to reset. the root folders to remove mods. However i can make something very quickly that *will* move things but wont remove them.

**Comment by CHollingworth** [comment]
Lamps filesystem is now in canary (check the discord its where canary builds are posted) which means im now actively working on C77 support i should have a c77 first test build either tonight or tomorrow.

**Comment by CHollingworth** [comment]
Well, ive made a test version and its live in the discord please give it a test and see if it functions as you expect.

**Comment by CHollingworth** [comment]
Basic Cyberpunk support is in, please enjoy the Canary-Stable release at the bottom of #50 until 1.0.9 is fully released.
