### ISSUE TITLE
Not an issue - Thank you so much!

### ISSUE THREAD

**Issue by BakiDance** [CHollingworth/Lamp#26]
Thank you so much for making this! I struggled for days getting WINE to run the windows mod manager. This is a godsend!
Sorry for using Github for this; I was going to leave a comment on Nexus, but there wasn't an option. I just had to express my thanks, haha.

**Comment by LT-Batman** [comment]
Same. When I first tried BG3MM I had to just create a fresh wine prefix and then wait for everything I needed to download into it. BG3MM worked once or twice then I had to reconfig it. Not to mention I constantly had to redirect everything back to Z:/ drive manually and use back dashes ( Z:\home\etc\etc\etc) which annoyed me for some reason.

Side note: there's actually a discussion section here on github you could use but lets just say that this is to get Mr. Hollingworth to open the posting section on Nexus.

**Comment by CHollingworth** [comment]
Thank you both, its been a pleasure to work on this and get help form you guys in the issues, ive opened up the nexus comments. Enjoy patch 5 guys!
