### ISSUE TITLE
[LAMP:ERROR:0] Could not load modlist.

### ISSUE THREAD

**Issue by alterNERDtive** [CHollingworth/Lamp#27]
This error message … uh … “pops up” whenever I start Lamp:

![image](https://github.com/CHollingworth/Lamp/assets/53827887/a9a0e77b-e11c-4a7f-80c3-38311a18ffe1)

It’s quite hard to read since it doesn’t actually pop up, but renders _behind_ the rest of the application.

**Comment by CHollingworth** [comment]
Ah apologies that would be fallout 4 having a fit that it can't load
properly, provided you bg3 mods are loading as normal.

**Comment by CHollingworth** [comment]
Hotfix incomming
