### ISSUE TITLE
Feature Request: some kind of progress / working indicator while deploying

### ISSUE THREAD

**Issue by alterNERDtive** [CHollingworth/Lamp#32]
I am running quite a few mods these days (triple digits :grimacing:), and deployment takes a while. Would be nice to know if it’s still running or hanging.

**Comment by alterNERDtive** [comment]
Also it seems like the deployment runs on the same thread as the UI, as the latter completely locks up.

**Comment by CHollingworth** [comment]
Will be added in 1.0.7
