### ISSUE TITLE
“Last Updated” column doesn’t … well, update.

### ISSUE THREAD

**Issue by alterNERDtive** [CHollingworth/Lamp#35]
**Describe the bug**
The “Last Updated” column never changes past the first time, which is the time and date at which you run version 1.0.7(+) for the first time.

**Expected behaviour**
When you update a mod, the “Last Updated” column changes to the time and date of the update.

**Screenshots**
![image](https://github.com/CHollingworth/Lamp/assets/53827887/afb115f9-a38e-4ca0-8301-28fb4f63941e)

**System Info (please complete the following information):**
 - Linux Flavour: Fedora 38
 - Window Manager: i3
 - Lamp Version: 1.0.7-pre

**Comment by CHollingworth** [comment]
Fixed in 1.0.7pr3
