### ISSUE TITLE
Lamp confuses main mod and optional extras

### ISSUE THREAD

**Issue by alterNERDtive** [CHollingworth/Lamp#36]
**Describe the bug**
Installing the _optional_ file from https://www.nexusmods.com/baldursgate3/mods/1420?tab=files on top of the default pack takes the optional file as an _update_ to the default pack instead of treating it as an additional mod.

**To Reproduce**
Steps to reproduce the behaviour:
1. Drag the “pack 1” file onto Lamp.
2. Mod gets added.
3. Drag the “pack 1 - optional” file onto Lamp
4. The main mod is “updated” with the new archive (see its tooltip).

**Expected behaviour**
The optional pack is added as a separate mod.

**System Info (please complete the following information):**
 - Linux Flavour: Fedora 38
 - Window Manager: i3
 - Lamp Version: 1.0.7-pre

**Comment by alterNERDtive** [comment]
This is probably going to be related to implementing #31 :)

**Comment by CHollingworth** [comment]
a simple (but bad) fix is to rename the optional file to put the hyphen after the word optional

**Comment by alterNERDtive** [comment]
That sounds like you are splitting at the first `-` to extract the modname? Shouldn’t you at least take everything in front of the mod ID, or ideally read it from the meta data?

**Comment by CHollingworth** [comment]
This should be closed as it was fixed a while ago #31 is still being looked into.

**Comment by alterNERDtive** [comment]
Still leaves the “mod archives contains several, modular mods” problem; but that’s a separate issue :)
