### ISSUE TITLE
A short HowTo for Mod Type selection

### ISSUE THREAD

**Issue by Jinxtaposition** [CHollingworth/Lamp#37]
Heya :) I LOVE that you're building Linux a proper mod manager! 

I must to admit to having been a little flummoxed at first on how to use it. But through trial and error I think I figured most of it out. I've decided to write it out and leave it here. Feel free to use any way you like, or start a manual, or delete, or stick on an USB stick and send it to a confused NASA engineer. All good ☺

------------------------------------------------

Hello everyone, here is some extra basic info that should help people find their way with this promising app ☺

### QUICK INSTALLATION
For installation, I simply downloaded it from [NexusMods](https://nexusmods.com), and then unpacked Lamp into: 
`~/Games/LampModManager`
But just choose whatever folder suits you best. Download it from Nexus and extract it into that folder. 
Then startup Lamp.

### GENERAL LAYOUT
First, here's an overview of what files and folders are what.

**Mod Manager Root Folder**:
`~/path/to/LampModManager`
	The folder you have Lamp installed in. 
	
**Mod Manager Settings Folder**:
`~/path/to/LampModManager/Lamp_Data/Config`
	This folder contains a file **conf.mdf** which contains the paths to your games, which is managed by the **Game Configuration** button in Lamp. If you have trouble deploying, ensure these settings are correct. 
	
**Mod Manager Mods List Folder**:
`~/path/to/LampModManager/Lamp_Data/Mod_Lists`
	This folder contains a file **BG3.mdf** which lists the installed games, mods, and their types. Basically what you see in LAMP's main window. Managed by LAMP, best left alone.
	
**Mod Manager Archives Folder**:
`~/path/to/LampModManager/Lamp_Data/Deployment/Archives`
	This folder contains the mod archives you drag on to the LAMP UI. Basically storage for your archives.
	
**Mod Staging Folder**:
`~/path/to/LampModManager/Lamp_Data`
	This contains subfolders where the to-be-deployed files are stored. (Upon deployment they are sent to the target folders below.)

### THE MOD TYPE OPTIONS
And here's an overview of the different Mod Types you can select in LAMP, and what they mean for deployment. Each Mod Type copies mods to a different part of the game directories, depending on what is required by the mod.

**Standard Mod**
Mods with **Standard Mod** selected get deployed from the LAMP Deployment folder:
`~/path/to/LampModManager/Lamp_Data/Deployment/Baldur's Gate 3/Mods`
 to the **BG AppData** folder:
`~/users/steamuser/Appdata/Local/Larian Studios/Baldur's Gate 3/Mods`
This basically goes for EVERY mod that uses nothing but a **.pak** file.
**Note**: I experienced one strange exception. **BagsBagsBags** was a mod I had installed manually before and worked fine, while now it has been deployed to the same folder; but when I load a save, I get an in-game error stating that BagsBagsBags is missing. I'm not sure what's going on there, it's the same version and BagsBagsBags.pak is in the Mods folder in the path above - same place as where it was installed before when I did it all manually. As far as I can tell, it should just work. I'm hoping CHollingworth can provide some more clarity.

**Engine Injection** mods get deployed from the LAMP NativeMods folder:
`~/path/to/LampModManager/Lamp_Data/Deployment/Baldur's Gate 3/bin/NativeMods`
to the BG3\bin\NativeMods folder:
`~/.steam/debian-installation/steamapps/common/Baldurs Gate 3/bin/NativeMods`
Use this option for mods that contain DLL's that need to be loaded with the game. 
Note : When I deploy **AMD_FSR2_for_BG3**, a mod that adds FSR2 support to BG3 for videocards, it doesn't appear to move ALL files, only the DLL's. This is probably by design by Lamp's author, but some mods have more than just DLL's to move around; AMD_FSR_for_BG3 for example also contains an .ini file and some license files, which in principle should also be copied. Hopefully CHollingworth can explain what I'm assuming/doing wrong, or else fix this for a future release.

**Bin Overwrite** mods get deployed from:
`~/path/to/LampModManager/Lamp_Data/Deployment/Baldur's Gate 3/bin`
to:
`~/.steam/debian-installation/steamapps/common/Baldurs Gate 3/bin`
This is useful for mods that need to directly overwrite what's present in the **/BG3/bin** folder, e.g. to replace the executable or one of the other core DLLs. (Only a few mods will need this.)

**Data Overwrite** mods get deployed from:
`~/path/to/LampModManager/Lamp_Data/Deployment/Baldur's Gate 3/Data`
to:
`~/.steam/debian-installation/steamapps/common/Baldurs Gate 3/Data/Generated/Public/SharedDev/Assets/Characters/_Models/path/to/some/modelfile`
This option is for mods that contain loose files, for example textures or meshes for characters or objects. You can tell by opening the mod zip file and seeing whether it has loose files in some long paths, or just a **.pak** file. If it's loose files, use the **Data Overwrite** option.

**Mod Fixer/ScriptExtender** Mod files get deployed from:
`~/path/to/LampModManager/Lamp_Data/Deployment/Baldur's Gate 3/Mods`
to:
`~/.steam/debian-installation/steamapps/compatdata/1086940/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldurs Gate 3/Mods`
So looks the same as the **Standard Mod** option. It may do more, I'm not sure. But since it says that it's specially meant for ModFixers, that's what i'll use it for :)

A FEW NOTES ON DEPLOYMENT
- I always do things step-by-step. For example, if I accidentally deployed a mod under the wrong Mod Type, I first Disable it, then hit Deploy button to ensure it is removed; only then do I change the Mod Type to whatever I should be using, and then hit Deploy again. 
- When you download a mod, unzip it first and look at the contents, then compare to the descriptions above to figure out what Mod Type to use.
- Don't forget to SHUT DOWN LAMP before you start to play.

Anyway, I hope this helps you guys get started more easily! If I'm missing or forgetting something, let me know! 
Best of luck and kind regards!

**Comment by CHollingworth** [comment]
Id like to thank you so much for this write-up i couldn't of done it better myself, if its alright with you ill add it to the new Usage Section of the wiki, with a few edits for 1.0.7

**Comment by CHollingworth** [comment]
Ill have a look into BagsBagsBags, as im unsure on that one.

Engine Injections Were for nativemods, and until now i didn't realise that they came with more, ill fix that for 1.0.7 as there was a toml fix aswell.

**Comment by Jinxtaposition** [comment]
Absolutely, feel free to add it :)
