### ISSUE TITLE
Mod Presets

### ISSUE THREAD

**Issue by alterNERDtive** [CHollingworth/Lamp#38]
**Is your feature request related to a problem? Please describe.**
Depending on who I am playing with (alone, my kids, friends, that other dude, …) I want/need a different set of mods, or even a subset of the same mods, but in a different version.

**Describe the solution you'd like**
It would be great if I could define separate presets for the same game. Bonus points for an option to toggle between tracking the “default” version of mods (or specific mods!) and keeping a preset-specific one around.

**Describe alternatives you've considered**
Well … since Lamp keeps everything in the working directory rn (unless that has been stealth-patched?) I have been considering keeping separate configuration directories. Which _does_ do the same thing, basically, but it would be cleaner to have it integrated into the tool. Plus the version tracking thing.

**Additional context**
BG3MM allows to have different presets for the _load order_, but not the … uh … “active mods”. So anything that overrides files for just being in the `Mods` folder has to be manually moved in and out of the folder. Lamp’s deployment approach deals with that problem; it would be nice to have it _also_ support presets, then.

**Comment by CHollingworth** [comment]
One of my goals is to add Profile support to Lamp, this should.. be
feasible within the next patch, however it requires a rewrite in the way
lamp save an loads modlists so 1.0.8 may take some time.
