### ISSUE TITLE
LAMP requires NativeMods directory to exist, otherwise deployment fails

### ISSUE THREAD

**Issue by dwm35** [CHollingworth/Lamp#39]
**Describe the bug**
For BG3, if the directory <game install directory>/bin/NativeMods does not exist, then deployment hangs.  On my PC this directory was not automatically created when the game was installed.

**Error message**
[LAMP:ERROR:4] Cleanup failed! Aborting Deployment

**To Reproduce**
Steps to reproduce the behaviour:
1. Rename <game install directory>/bin/NativeMods
2. Start LAMP
3. Click [Deploy]
4. Click [Start]
5. Error message shown

**Expected behaviour**
LAMP should automatically create the foloder if it is missing

**System Info (please complete the following information):**
 - Linux Flavour: Linux Mint 21.2, Cinnamon edition
 - Window Manager: Mutter
 - Lamp Version: 1.0.7

**Additional context**
A workaround is to manually create the folder.  This is easy, once you know what the issue is.  If automatically creating the directory is undesirable, then maybe include the missing folder name in the error message?

**Comment by CHollingworth** [comment]
Ah yes I'll add this one to the faq for now, a fix is planned for this in
1.0.8
