### ISSUE TITLE
LAMP crashes intermittently on deploy

### ISSUE THREAD

**Issue by Jinxtaposition** [CHollingworth/Lamp#40]
**Describe the bug**
LAMP crashes quite regularly when I try to deploy. Then, when I restart it and try it a few times more, it succeeds (or at least, doesn't crash). 
I've been breaking my head trying to fgure out the cause. So far, I can't blame any specific mods, it looks more like it just stumbles over itself somehow. The likelyhood increases the more mods are installed. 

**Error message**
None, LAMP just exits

**To Reproduce**
Steps to reproduce the behaviour:
- Download a few dozen mods. Specifically I have: several UI enhancements, bag and container improvers, some mods to speed up launch, the core mods like ModFixer and Script Extender, and several character skins. I can provide a full list if you prefer.
- Install them, set their Mod Types, Enable and Deploy. 

**Expected behaviour**
No crash :)

**Screenshots**
none

**System Info (please complete the following information):**
 - Linux Flavour: Ubuntu 22.04
 - Window Manager: Wayland
 - Lamp Version: 1.07

**Additional context**
Please let me know which log files you would like and I'll be happy to dig them up.

**Comment by CHollingworth** [comment]
That's certainly a curious one, I'd be very interested in seeing a gdb log
result of the cash state.

**Comment by Jinxtaposition** [comment]
Heya :)
I just updated to 1.08, saw that it also has logging. Awesome!

So I had a go at it (I started with a completely clean build because why not) and it no longer crashes! So whatever you did, it fixed something, tyvm :)  I'll keep playing with it the coming while and drop any feedback I can come up with. So as far as I'm concerned this issue can be closed. 

One (minor) side note: while trying to select the BG3 Steam Directory and AppData Directory, Ubuntu comes with the "Program inactive - wait or force close" warning. Not a real hindrance (and Ubuntu is a bit trigger-happy in this regard) but I thought I'd point it out.

**Comment by CHollingworth** [comment]
Thats me forgetting to move the file picker code to a separate thread, ill get on that one. 

Glad to hear its fixed itself up
