### ISSUE TITLE
Missing     third-party/json/json.hpp

### ISSUE THREAD

**Issue by aclater** [CHollingworth/Lamp#45]
**Describe the bug**
CMakeLists.txt line 9 refers to third-party/json/json.hpp, which is not included

**Error message**
`cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=ninja -G Ninja -S ./ -B ./Build
-- Configuring done (0.1s)
CMake Error at CMakeLists.txt:9 (add_executable):
  Cannot find source file:

    third-party/json/json.hpp

CMake Error at CMakeLists.txt:9 (add_executable):
  No SOURCES given to target: Lamp

CMake Generate step failed.  Build files cannot be regenerated correctly.
`

**To Reproduce**
Steps to reproduce the behaviour:
1. git clone  https://github.com/CHollingworth/Lamp
2. cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=ninja -G Ninja -S ./ -B ./Build
3. See error

**Expected behaviour**
LAMP should compile as delivered

**Comment by CHollingworth** [comment]
Huh somehow json got skipped from the commit, ill fix that now

**Comment by CHollingworth** [comment]
Thats fixed thank you for pointing it out!
