### ISSUE TITLE
provide automated versioned build system

### ISSUE THREAD

**Issue by airtonix** [CHollingworth/Lamp#46]
**Is your feature request related to a problem? Please describe.**

- follow conventional commit pattern in PR titles
- merging PRs to `main` triggers a process that creates or keeps a release PR updated
- merging the release PR computes a version and makes a release build uploaded to that release tag
- a generated CHANGELOG is created or updated.

**Describe the solution you'd like**

release-please

**Describe alternatives you've considered**

**Additional context**

I've done similar work for https://github.com/nvim-telescope/telescope-fzf-native.nvim/pull/93 (yet to be merged as they don't seem to be in a hurry)

**Comment by CHollingworth** [comment]
Ill close this for now, as we are actively pushing the changes to 1.0.9
