### ISSUE TITLE
add pugixml as a listed depencancy

### ISSUE THREAD

**Issue by VoidAndCaffeine** [CHollingworth/Lamp#55]
**Error message**
./Lamp: error while loading shared libraries: libpugixml.so.1: cannot open shared object file: No such file or directory

**To Reproduce**
attempt to run the program after installing the listed dependencies on arch linux.
install pugixml to fix the above error.

**System Info (please complete the following information):**
 - Arch linux
 - Hyprland
 - Lamp v1.0.8

**Comment by CHollingworth** [comment]
Added, apologies for the confusion.
