### ISSUE TITLE
Hitting “deploy” just creates an empty mod list

### ISSUE THREAD

**Issue by alterNERDtive** [CHollingworth/Lamp#6]
Well, and technically a `data` folder in the installation path (should use `Data`). Data/bin overwrites don’t seem to result in anything, either (disabled in the screenshot, but I did try with them enabled, don’t worry ;)).

![image](https://github.com/CHollingworth/Lamp/assets/53827887/e7a5b61f-42d2-40bd-ae43-369d221b4de6)

![image](https://github.com/CHollingworth/Lamp/assets/53827887/eede69e8-2787-4c96-bd31-46b055088bd9)

Cool project though, looking forward to the day when I can ditch the buggy (under wine) BG3ModManager :)

**Comment by alterNERDtive** [comment]
Huh. I did specifically fix that after noticing, but apparently it either didn’t take or I messed it up again during troubleshooting.

Problem is still the same, though, after changing the folder.

**Comment by CHollingworth** [comment]
Could you append a screen shot of Lamp_Data/ , Lamp_Data/Deployment/Baldur's Gate 3 , and confirm if Lamp_Data/Deployment/Baldur's Gate 3/PlayerProfiles contains modsettings.lsx

**Comment by alterNERDtive** [comment]
```bash
% ll Lamp_Data
total 0
drwxr-xr-x. 1 daniel daniel 30 12. Sep 21:37 Archives
drwxr-xr-x. 1 daniel daniel 16 12. Sep 21:32 Config
drwxr-xr-x. 1 daniel daniel 52 12. Sep 21:32 Deployment
drwxr-xr-x. 1 daniel daniel 14 12. Sep 22:34 Mod_Lists
```

``bash
% ll Lamp_Data/Deployment/Baldur\'s\ Gate\ 3
total 0
drwxr-xr-x. 1 daniel daniel 20 12. Sep 22:31 bin
drwxr-xr-x. 1 daniel daniel  0 12. Sep 22:31 data
drwxr-xr-x. 1 daniel daniel  0 12. Sep 22:31 ext
drwxr-xr-x. 1 daniel daniel  0 12. Sep 22:31 Mods
drwxr-xr-x. 1 daniel daniel 12 12. Sep 22:31 PlayerProfiles
```

```bash
% cat Lamp_Data/Deployment/Baldur\'s\ Gate\ 3/PlayerProfiles/Public/modsettings.lsx
<?xml version="1.0"?>
<save>
        <version major="4" minor="0" revision="9" build="331" />
        <region id="ModuleSettings">
                <node id="root">
                        <children>
                                <node id="ModOrder">
                                        <children />
                                </node>
                                <node id="Mods">
                                        <children />
                                </node>
                        </children>
                </node>
        </region>
</save>
```

**Comment by CHollingworth** [comment]
I think ive caught the issue, i cant see to replicate it on my end, ill push a hotfix very quickly, should just be a drop in replacement.

**Comment by alterNERDtive** [comment]
IDK if that is what you mean, but I think there is a bug in saving the settings file:

```bash
% cat Lamp_Data/Config/conf.mdf
<?xml version="1.0"?>
<root>
        <game name="LAMP CONFIG">
                <ShowIntroMenu>0</ShowIntroMenu>
                <CurrentGame>-1</CurrentGame>
        </game>
        <game name="Baldur's Gate 3">
                <installDirPath>/home/daniel/.local/share/Steam/steamapps/common/Baldurs Gate 3</installDirPath>
                <appDataPath>/home/daniel/.local/share/Steam/steamapps/compatdata/1086940/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3/PlayerProfiles</appDataPath>
                <appDataPath>/home/daniel/.local/share/Steam/steamapps/compatdata/1086940/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3</appDataPath>
                <appDataPath>/home/daniel/.local/share/Steam/steamapps/compatdata/1086940/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3</appDataPath>
        </game>
</root>
```

**Comment by CHollingworth** [comment]
If the Lamp_Data/Deployment/Baldur's Gate 3/Mods folder is empty, with some standard mods enabled after attempting with the hotfix, could you run the program from terminal and send me the output after attempting a deploy.

**Comment by alterNERDtive** [comment]
Sure, assuming it does actually log something then :)

**Comment by CHollingworth** [comment]
> IDK if that is what you mean, but I think there is a bug in saving the settings file:
> 
> ```shell
> % cat Lamp_Data/Config/conf.mdf
> <?xml version="1.0"?>
> <root>
>         <game name="LAMP CONFIG">
>                 <ShowIntroMenu>0</ShowIntroMenu>
>                 <CurrentGame>-1</CurrentGame>
>         </game>
>         <game name="Baldur's Gate 3">
>                 <installDirPath>/home/daniel/.local/share/Steam/steamapps/common/Baldurs Gate 3</installDirPath>
>                 <appDataPath>/home/daniel/.local/share/Steam/steamapps/compatdata/1086940/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3/PlayerProfiles</appDataPath>
>                 <appDataPath>/home/daniel/.local/share/Steam/steamapps/compatdata/1086940/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3</appDataPath>
>                 <appDataPath>/home/daniel/.local/share/Steam/steamapps/compatdata/1086940/pfx/drive_c/users/steamuser/AppData/Local/Larian Studios/Baldur's Gate 3</appDataPath>
>         </game>
> </root>
> ```

could you attempt removing all <appDataPath> lines and setting it in application again this is definitely something that requires attention

**Comment by alterNERDtive** [comment]
> could you run the program from terminal and send me the output after attempting a deploy.

[lamp_log.txt](https://github.com/CHollingworth/Lamp/files/12597526/lamp_log.txt)

**Comment by CHollingworth** [comment]
Ah now that, makes alot of sense and ive realised ive missed glaring requirement, installing p7zip-full should fix the issues, i had assumed it was in most standard distros.

**Comment by CHollingworth** [comment]
does /usr/lib/p7zip/7z.so exist? this should be the path to the library its attempting to access, according to the log its a  "Bad file descriptor". if not i'm currently attempting to bundle it with the program

**Comment by alterNERDtive** [comment]
It’s under `/usr/libexec/` on Fedora, apparently.

**Comment by CHollingworth** [comment]
Huh, well that's interesting, for now ill quickly add a selection button on the menu bar for it should only take 10 mins

**Comment by alterNERDtive** [comment]
You could just look in `libexec` if it doesn’t exist in `lib`, and throw an error if neither can be found.

**Comment by CHollingworth** [comment]
> You could just look in `libexec` if it doesn’t exist in `lib`, and throw an error if neither can be found.

That would be alot easier, i've gone for that approach. ill upload the hotfix now

**Comment by Azurion42** [comment]
I've got it running now with the glfw installed, but now when I drag and drop paks onto the window, they don't load. Launched it via console and it says things were dropped, but they don't show up in the UI itself, and hitting deploy leaves me with a very bare list. Using 1.0.3.1 from Nexus and the v1.0.3 Lamp X11 x64 HOTFIX 1 version from this site. I'm also on Fedora 38 KDE Wayland, if that makes a difference.

**Comment by CHollingworth** [comment]
> I've got it running now with the glfw installed, but now when I drag and drop paks onto the window, they don't load. Launched it via console and it says things were dropped, but they don't show up in the UI itself, and hitting deploy leaves me with a very bare list. Using 1.0.3.1 from Nexus and the v1.0.3 Lamp X11 x64 HOTFIX 1 version from this site. I'm also on Fedora 38 KDE Wayland, if that makes a difference.

The tool works with the archives not pak files directly. if you are dropping paks onto the window itself it wont add them to the listings, make sure to enable them and select the correct mod type, i highly recomend looking at the nexus mods images for what type should be selected.

**Comment by Azurion42** [comment]
> > I've got it running now with the glfw installed, but now when I drag and drop paks onto the window, they don't load. Launched it via console and it says things were dropped, but they don't show up in the UI itself, and hitting deploy leaves me with a very bare list. Using 1.0.3.1 from Nexus and the v1.0.3 Lamp X11 x64 HOTFIX 1 version from this site. I'm also on Fedora 38 KDE Wayland, if that makes a difference.
> 
> The tool works with the archives not pak files directly. if you are dropping paks onto the window itself it wont add them to the listings, make sure to enable them and select the correct mod type, i highly recomend looking at the nexus mods images for what type should be selected.

Oooooh, I see it now, I'm dumb. Thank you.

**Comment by Slade0120** [comment]
This seems to be happening, still. Lamp puts the mods in place, but does not actually update the modsettings.lsx file.

**Comment by CHollingworth** [comment]
Could you check your on the latest version and send me the terminal output,
one thing to ask is if the modsettings file exists within the app data
folder as it copies it.

You should also have a modsettings file within lamp_data could you check if
it's there and if its populated.

It could be also due to a problem I'm patching where the mods are in a sub
folder of the archive.

**Comment by alterNERDtive** [comment]
> This seems to be happening, still. Lamp puts the mods in place, but does not actually update the modsettings.lsx file.

Check #14

**Comment by CHollingworth** [comment]
Ill be closing this one for now as #14 seems to put a better point on it and ill be working to fix it now.

> > This seems to be happening, still. Lamp puts the mods in place, but does not actually update the modsettings.lsx file.
> 
> Check #14
