### ISSUE TITLE
Modsetting.lsx file not upadting with all mods

### ISSUE THREAD

**Issue by awinborne415** [CHollingworth/Lamp#62]
I have about 30 mods and it adds all of them to the mod folder but the modsetting.lsx file is only updated with 3 of them. Any ideas why this would happen? I have the newest version 1.0.8

**Comment by CHollingworth** [comment]
This is a known issue with 1.0.8, as it cant extract the metadata from newer mods. A fix will be released alongside 1.0.9, for now the best solution is trying the canary version available on the discord.
