### ISSUE TITLE
Add support for flatpak installed or alternative game dir locations

### ISSUE THREAD

**Issue by BobbyByrne** [CHollingworth/Lamp#73]
Please add support for choosing the game folder location. This will support flatpak installs and likely other installation methods. 

If it's possible to get Lamp to work in its current state, any helpful instructions would be appreciated. I haven't tried it, but could symlinking the game dir to the location Lamp expects work?

**Comment by alterNERDtive** [comment]
Have you … looked at the settings menu?

**Comment by BobbyByrne** [comment]
I'm dumb lol
Thanks
