### ISSUE TITLE
Won't Start

### ISSUE THREAD

**Issue by Azurion42** [CHollingworth/Lamp#8]
I've double clicked on it to try and get it to launch but it won't, for whatever reason. I have Zenity installed, I've got Vulkan. I right click on it but it won't tell me what to use to launch it, I've even opened a terminal in the folder I put it in and did a ./Lamp to run it, and it comes back with 
`./Lamp: error while loading shared libraries: libglfw.so.3: cannot open shared object file: No such file or directory`

Is there something I'm doing wrong?

Edit: I am on Fedora 38 KDE

**Comment by alterNERDtive** [comment]
```bash
% dnf provides */libglfw.so.3
Last metadata expiration check: 7:12:53 ago on Di 12 Sep 2023 23:21:42 CEST.
glfw-1:3.3.8-2.fc38.i686 : A cross-platform multimedia library
Repo        : fedora
Matched from:
Filename    : /usr/lib/libglfw.so.3

glfw-1:3.3.8-2.fc38.x86_64 : A cross-platform multimedia library
Repo        : @System
Matched from:
Filename    : /usr/lib64/libglfw.so.3

glfw-1:3.3.8-2.fc38.x86_64 : A cross-platform multimedia library
Repo        : fedora
Matched from:
Filename    : /usr/lib64/libglfw.so.3
```

→ install `glfw`.

**Comment by CHollingworth** [comment]
Thank you! i missed that when writing the requirements, many thanks!
