### ISSUE TITLE
[Requirements] List 'xterm' as a requirement.

### ISSUE THREAD

**Issue by Unhall0w3d** [CHollingworth/Lamp#9]
Upon launching the executable I received an error indicating xterm could not be found. On Arch I can install xterm, but the program should either be able to adapt and use a variable or other established value to draw the user's default terminal from, or, xterm should be listed in the requirements here, and on NexusMods.

Additionally, even after installing xterm, the program does not launch on Manjaro SwayWM (Wayland), fully up to date.

OS: Manjaro Linux x86_64 
Kernel: 6.5.0-1-MANJARO 
Shell: zsh 5.9 
WM: sway 
Terminal: foot 

No error is produced, it just fails to run or produce anything on screen.

**Comment by CHollingworth** [comment]
I shall have to look into supporting other WM, ill add X11 to the requirements for now, and look into that.

**Comment by CHollingworth** [comment]
It may be worth attempting a build from source

**Comment by CHollingworth** [comment]
After looking into it, you'll need to build from source. it appears that in place of the standard glfw3 install you'll need to use glfw-wayland unfortunately i could not get the vm to function properly, i apologise for not being able to help further.
